namespace Shiny.Maui.AI;

/// <summary>
/// Represents a single chat message persisted in the message store.
/// </summary>
/// <param name="Id">Unique identifier for the message.</param>
/// <param name="Message">The text content of the message.</param>
/// <param name="Timestamp">When the message was sent or received.</param>
/// <param name="Direction">Whether the message was sent by the user or the AI.</param>
public record AiChatMessage(
    string Id,
    string Message,
    DateTimeOffset Timestamp,
    ChatMessageDirection Direction
);

/// <summary>
/// Indicates the origin of a chat message.
/// </summary>
public enum ChatMessageDirection
{
    /// <summary>The message was sent by the user.</summary>
    User,
    /// <summary>The message was generated by the AI.</summary>
    AI
}